import { CapabilityBadge, LoadingPanel, PageHeader, Panel, StatusBadge } from "@/components/PlatformUI";
import { Button } from "@/components/ui/button";
import { useEnterpriseRole } from "@/contexts/RoleContext";
import { trpc } from "@/lib/trpc";
import { rolePermissionMatrix } from "@shared/domain";
import { Braces, Check, Code2, Copy, Database, KeyRound, LockKeyhole, Plus, RadioTower, Server, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

export function Connectors() {
  const { data, isLoading } = trpc.platform.connectors.list.useQuery();
  if (isLoading || !data) return <LoadingPanel />;
  return <><PageHeader eyebrow="Connector runtime" title="连接器管理" description="注册外部系统适配器，以机器可读契约声明 Query、Function、Proposal、Action、Event 五类能力。" actions={<Button className="rounded-xl bg-teal-300 text-[#061718] hover:bg-teal-200" onClick={() => toast("连接器注册向导将在下一阶段接入真实凭据") }><Plus className="mr-2 h-4 w-4" />注册连接器</Button>} />
    <div className="grid gap-5 xl:grid-cols-3">{data.map(connector => <Panel key={connector.key} className="overflow-hidden"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl border border-teal-300/15 bg-teal-300/[0.07]"><Server className="h-5 w-5 text-teal-300" /></div><StatusBadge status={connector.status} /></div><p className="mt-5 text-lg font-semibold text-white">{connector.name}</p><p className="mt-1 text-[10px] text-slate-600">{connector.system} · {connector.auth}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-black/15 p-3"><p className="text-lg font-semibold text-white">{connector.latency}ms</p><p className="text-[9px] text-slate-600">P95 latency</p></div><div className="rounded-xl bg-black/15 p-3"><p className="text-lg font-semibold text-white">{connector.availability}</p><p className="text-[9px] text-slate-600">30 天可用性</p></div></div><div className="mt-5 space-y-2">{connector.capabilities.map(cap => <div key={cap.key} className="rounded-xl border border-white/[0.05] bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><CapabilityBadge kind={cap.kind} /><span className={`text-[9px] ${cap.risk === "高" ? "text-red-300" : cap.risk === "中" ? "text-orange-300" : "text-teal-300"}`}>{cap.risk}风险</span></div><p className="mt-3 text-xs font-medium text-slate-200">{cap.name}</p><p className="mt-1 text-[9px] leading-4 text-slate-600">{cap.description}</p>{cap.approval ? <p className="mt-2 flex items-center gap-1 text-[9px] text-orange-300"><LockKeyhole className="h-3 w-3" />需要审批</p> : null}</div>)}</div></Panel>)}</div>
  </>;
}

export function Gateway() {
  const { data, isLoading } = trpc.platform.gateway.manifest.useQuery();
  if (isLoading || !data) return <LoadingPanel />;
  return <><PageHeader eyebrow="Agent access plane" title="MCP/API 网关" description="向 AgenticX 和 Near 终端智能体暴露统一对象与 Action 能力；默认只读，写操作必须通过策略、审批与幂等门控。" actions={<Button variant="outline" className="rounded-xl border-white/10 bg-white/[0.03]" onClick={() => { navigator.clipboard.writeText("https://gateway.enterprise.example/mcp"); toast.success("示例端点已复制"); }}><Copy className="mr-2 h-4 w-4" />复制端点</Button>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_360px]">
      <Panel title="能力清单" eyebrow="Machine-readable manifest"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b border-white/[0.06] text-[9px] uppercase tracking-wider text-slate-600"><th className="pb-3">Tool</th><th className="pb-3">Kind</th><th className="pb-3">风险</th><th className="pb-3">审批</th><th className="pb-3">说明</th></tr></thead><tbody>{data.endpoints.map(endpoint => <tr key={endpoint.tool} className="border-b border-white/[0.04]"><td className="py-4 font-mono text-[10px] text-teal-200">{endpoint.tool}</td><td className="py-4"><CapabilityBadge kind={endpoint.kind} /></td><td className="py-4 text-slate-400">{endpoint.risk}</td><td className="py-4"><StatusBadge status={endpoint.approval ? "需要" : "无需"} /></td><td className="py-4 text-slate-500">{endpoint.description}</td></tr>)}</tbody></table></div></Panel>
      <div className="space-y-5"><Panel title="网关身份" eyebrow="Trusted callers"><div className="space-y-3">{data.allowedCallers.map(caller => <div key={caller} className="flex items-center gap-3 rounded-xl border border-teal-300/10 bg-teal-300/[0.04] p-4"><div className="grid h-8 w-8 place-items-center rounded-xl bg-teal-300/10"><RadioTower className="h-4 w-4 text-teal-300" /></div><div><p className="text-xs font-medium text-white">{caller}</p><p className="mt-1 text-[9px] text-slate-600">身份委托 · 范围 Token · 全链路审计</p></div></div>)}</div></Panel><Panel title="协议状态" eyebrow="Gateway contract"><div className="space-y-3">{data.protocols.map(item => <div key={item} className="flex items-center justify-between rounded-xl bg-black/15 p-3 text-xs"><span className="font-mono text-slate-300">{item}</span><StatusBadge status="启用" /></div>)}<div className="rounded-xl border border-orange-300/10 bg-orange-300/[0.04] p-4"><p className="text-[10px] text-orange-200">默认模式 · {data.defaultMode}</p><p className="mt-2 text-[9px] leading-4 text-slate-600">浏览器不持有企业凭据。真实协议适配器部署在企业网关侧。</p></div></div></Panel><Panel title="调用上下文" eyebrow="Required envelope"><pre className="overflow-x-auto rounded-xl bg-black/25 p-4 font-mono text-[9px] leading-5 text-slate-400">{`{\n  caller: "AgenticX",\n  user_id: "U-2048",\n  tenant: "obsidian",\n  object_id: "OBJ-O-4021",\n  scopes: ["read", "propose"]\n}`}</pre></Panel></div>
    </div></>;
}

export function Access() {
  const { data, isLoading } = trpc.platform.access.matrix.useQuery();
  const { role } = useEnterpriseRole();
  if (isLoading || !data) return <LoadingPanel />;
  return <><PageHeader eyebrow="Zero-trust role model" title="角色权限控制" description="固定四类企业角色，并将读取、提案、审批、执行拆成独立授权。角色切换只影响演示视图，真实授权由服务端策略决定。" />
    <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-4">{data.matrix.map(item => <Panel key={item.role} className={item.role === role ? "ring-1 ring-teal-300/35" : ""}><div className="flex items-start justify-between"><div className={`grid h-10 w-10 place-items-center rounded-2xl ${item.role === role ? "bg-teal-300/15 text-teal-300" : "bg-white/[0.04] text-slate-500"}`}><KeyRound className="h-5 w-5" /></div>{item.role === role ? <StatusBadge status="当前视角" /> : null}</div><h3 className="mt-5 text-base font-semibold text-white">{item.role}</h3><p className="mt-2 min-h-10 text-[10px] leading-5 text-slate-500">{item.scope}</p><div className="mt-5 space-y-2">{Object.entries(item.permissions).map(([permission, enabled]) => <div key={permission} className="flex items-center justify-between rounded-xl border border-white/[0.04] bg-black/10 p-3"><span className="text-xs text-slate-400">{permission}</span><span className={`grid h-6 w-6 place-items-center rounded-full ${enabled ? "bg-teal-300/10 text-teal-300" : "bg-red-300/10 text-red-300"}`}>{enabled ? <Check className="h-3 w-3" /> : <LockKeyhole className="h-3 w-3" />}</span></div>)}</div></Panel>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_360px]"><Panel title="权限决策过程" eyebrow="Policy evaluation"><div className="grid gap-3 md:grid-cols-4">{["用户身份", "企业角色", "对象范围", "能力风险"].map((step, index) => <div key={step} className="rounded-xl border border-white/[0.05] bg-black/10 p-4"><p className="text-[9px] text-teal-300">0{index + 1}</p><p className="mt-3 text-xs font-medium text-slate-200">{step}</p><p className="mt-2 text-[9px] leading-4 text-slate-600">{["确认登录用户与终端调用方", "解析四类角色及组织关系", "限制可访问的统一企业对象", "结合 Query / Action 风险等级"][index]}</p></div>)}</div></Panel><Panel title="当前视角" eyebrow="Demo role"><p className="text-2xl font-semibold text-white">{role}</p><div className="mt-4 grid grid-cols-4 gap-2">{Object.entries(rolePermissionMatrix[role]).map(([key, value]) => <div key={key} className={`rounded-xl p-3 text-center ${value ? "bg-teal-300/10" : "bg-white/[0.03]"}`}><p className={`text-sm font-semibold ${value ? "text-teal-200" : "text-slate-700"}`}>{value ? "YES" : "NO"}</p><p className="mt-1 text-[8px] text-slate-600">{key}</p></div>)}</div></Panel></div>
  </>;
}
