import { LoadingPanel, PageHeader, Panel, StatusBadge } from "@/components/PlatformUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Check, ChevronRight, Database, Fingerprint, GitBranch, Network, Plus, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

export function Objects() {
  const { data: objects, isLoading } = trpc.platform.objects.list.useQuery();
  const [selectedId, setSelectedId] = useState("OBJ-O-4021");
  const { data: graph } = trpc.platform.objects.graph.useQuery({ objectId: selectedId });
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => objects?.filter(item => `${item.name}${item.id}${item.typeName}`.toLowerCase().includes(search.toLowerCase())) ?? [], [objects, search]);
  if (isLoading || !objects) return <LoadingPanel />;
  return <>
    <PageHeader eyebrow="Semantic object graph" title="对象与关系浏览器" description="按统一企业对象查询跨系统状态、关系和证据。源系统仍保持事实权威，本体层提供一致语义与来源追溯。" actions={<div className="relative"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-600" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索对象" className="w-64 border-white/[0.07] bg-black/20 pl-9 text-xs" /></div>} />
    <div className="grid min-h-[680px] gap-5 xl:grid-cols-[320px_1fr_360px]">
      <Panel title={`企业对象 · ${filtered.length}`} eyebrow="Object index" className="h-fit">
        <div className="space-y-2">{filtered.map(item => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full rounded-xl border p-3 text-left ${selectedId === item.id ? "border-teal-300/20 bg-teal-300/[0.08]" : "border-white/[0.04] bg-black/10 hover:bg-white/[0.03]"}`}><div className="flex items-center justify-between"><span className="text-[9px] font-medium text-teal-300">{item.typeName}</span><StatusBadge status={item.status} /></div><p className="mt-2 truncate text-xs font-medium text-slate-200">{item.name}</p><p className="mt-1 font-mono text-[9px] text-slate-600">{item.id} · {item.source}</p></button>)}</div>
      </Panel>
      <Panel title="关系画布" eyebrow="Cross-system relations" className="min-h-[620px]">
        {graph ? <div className="micro-grid relative min-h-[520px] overflow-hidden rounded-2xl border border-white/[0.05] bg-black/15 p-8">
          <div className="absolute inset-x-14 top-1/2 h-px bg-gradient-to-r from-transparent via-teal-300/30 to-transparent" />
          <div className="grid min-h-[450px] place-items-center"><div className="relative grid h-32 w-32 place-items-center rounded-full border border-orange-300/30 bg-orange-300/10 text-center shadow-[0_0_70px_rgba(194,88,32,.15)]"><Network className="mb-2 h-5 w-5 text-orange-300" /><p className="px-3 text-xs font-semibold text-white">{graph.focus.name}</p><p className="mt-1 font-mono text-[8px] text-orange-200/70">{graph.focus.id}</p></div></div>
          {graph.nodes.filter(item => item.id !== graph.focus.id).map((node, index) => { const positions = ["left-8 top-12", "right-8 top-24", "left-16 bottom-10"]; return <div key={node.id} className={`absolute ${positions[index] ?? "right-10 bottom-12"} w-44 rounded-2xl border border-teal-300/15 bg-[#0b292b]/95 p-4 shadow-2xl`}><p className="text-[9px] text-teal-300">{node.typeName}</p><p className="mt-1 truncate text-xs font-medium text-white">{node.name}</p><p className="mt-1 font-mono text-[8px] text-slate-600">{node.id}</p></div>; })}
          <div className="absolute bottom-5 right-5 rounded-xl border border-white/[0.05] bg-black/30 px-3 py-2 text-[9px] text-slate-500">关系来自 {graph.edges.length} 条可追溯证据</div>
        </div> : null}
      </Panel>
      <Panel title="对象详情与证据" eyebrow="Authoritative context" className="h-fit">
        {graph ? <><div className="rounded-xl border border-white/[0.05] bg-black/15 p-4"><p className="text-lg font-semibold text-white">{graph.focus.name}</p><div className="mt-3 flex items-center gap-2"><StatusBadge status={graph.focus.status} /><span className="text-[9px] text-slate-600">源：{graph.focus.source}</span></div></div><div className="mt-4 space-y-2">{Object.entries(graph.focus.properties).map(([key, value]) => <div key={key} className="flex items-center justify-between border-b border-white/[0.04] py-2 text-xs"><span className="text-slate-500">{key}</span><span className="font-medium text-slate-200">{String(value)}</span></div>)}</div><div className="mt-5 space-y-3">{graph.edges.map(edge => <div key={`${edge.from}-${edge.to}`} className="rounded-xl border border-white/[0.05] bg-black/10 p-3"><div className="flex items-center gap-2 text-xs text-slate-200"><GitBranch className="h-3.5 w-3.5 text-teal-300" />{edge.type}</div><p className="mt-2 text-[9px] leading-4 text-slate-500">{edge.evidence}</p><p className="mt-2 text-[9px] text-teal-300">置信度 {edge.confidence}%</p></div>)}</div></> : null}
      </Panel>
    </div>
  </>;
}

export function OntologyStudio() {
  const { data, isLoading } = trpc.platform.ontology.workspace.useQuery();
  const [activeType, setActiveType] = useState("Order");
  if (isLoading || !data) return <LoadingPanel />;
  const selected = data.objectTypes.find(item => item.key === activeType) ?? data.objectTypes[0];
  const steps = ["对象类型", "属性", "关系", "约束", "函数", "Action", "版本"];
  return <><PageHeader eyebrow="Ontology-as-code workspace" title="本体工作室" description="以低代码方式维护对象、关系、约束、Function 与 Action 契约；每次变更进入版本、评审和发布流程。" actions={<Button className="rounded-xl bg-teal-300 text-[#061718] hover:bg-teal-200"><Plus className="mr-2 h-4 w-4" />新建对象类型</Button>} />
    <div className="mb-5 grid grid-cols-2 gap-2 rounded-2xl border border-white/[0.06] bg-black/15 p-2 md:grid-cols-7">{steps.map((step, index) => <div key={step} className={`flex items-center gap-2 rounded-xl px-3 py-3 text-[10px] ${index === 0 ? "bg-teal-300/10 text-teal-200" : "text-slate-600"}`}><span className={`grid h-5 w-5 place-items-center rounded-full border ${index === 0 ? "border-teal-300/30" : "border-white/[0.06]"}`}>{index + 1}</span>{step}</div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[280px_1fr_340px]">
      <Panel title="对象类型" eyebrow="Schema registry"><div className="space-y-2">{data.objectTypes.map(item => <button key={item.key} onClick={() => setActiveType(item.key)} className={`w-full rounded-xl border p-3 text-left ${activeType === item.key ? "border-teal-300/20 bg-teal-300/[0.08]" : "border-white/[0.04] bg-black/10"}`}><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-teal-300">{item.key}</span><StatusBadge status={item.status} /></div><p className="mt-2 text-xs font-medium text-slate-200">{item.name}</p><p className="mt-1 text-[9px] text-slate-600">{item.properties} 属性 · {item.relations} 关系 · {item.actions} Action</p></button>)}</div></Panel>
      <Panel title={`${selected.name} / ${selected.key}`} eyebrow="Visual schema editor"><div className="rounded-2xl border border-white/[0.06] bg-black/15 p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-widest text-teal-300">Object type</p><h3 className="mt-2 text-xl font-semibold text-white">{selected.name}</h3></div><span className="font-mono text-xs text-slate-500">{selected.version}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{["order_number · string · required", "promise_date · datetime · required", "customer · relation<Customer>", "delivery_risk · number · computed", "contract · relation<Contract>", "source_system · enum"].map(item => <div key={item} className="rounded-xl border border-white/[0.05] bg-[#0a2426] p-3 font-mono text-[10px] text-slate-300">{item}</div>)}</div></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[{title:"约束",items:["promise_date ≥ created_at","customer 必须已验证"]},{title:"Functions",items:["calculate_delivery_risk","estimate_penalty"]},{title:"Actions",items:["adjust_schedule","split_delivery"]}].map(section => <div key={section.title} className="rounded-xl border border-white/[0.05] bg-black/10 p-4"><p className="text-[10px] uppercase tracking-wider text-orange-300">{section.title}</p>{section.items.map(item => <p key={item} className="mt-3 font-mono text-[9px] text-slate-400">{item}</p>)}</div>)}</div></Panel>
      <Panel title="版本时间线" eyebrow="Governed changes"><div className="space-y-4">{data.versions.map((version, index) => <div key={version.version} className="relative pl-6"><span className={`absolute left-0 top-1 h-2.5 w-2.5 rounded-full ${index === 0 ? "bg-teal-300 shadow-[0_0_12px_rgba(94,234,212,.7)]" : "bg-slate-700"}`} /><div className="absolute bottom-[-18px] left-[4px] top-4 w-px bg-white/[0.06]" /><div className="flex items-center justify-between"><span className="font-mono text-xs text-slate-200">{version.version}</span><StatusBadge status={version.status} /></div><p className="mt-2 text-[10px] leading-4 text-slate-500">{version.change}</p><p className="mt-2 text-[9px] text-slate-700">{version.author} · {version.date}</p></div>)}</div></Panel>
    </div></>;
}

export function Identity() {
  const { data, isLoading } = trpc.platform.identity.mappings.useQuery();
  if (isLoading || !data) return <LoadingPanel />;
  const customerMappings = data.filter(item => item.objectId === "OBJ-C-1002");
  return <><PageHeader eyebrow="Entity resolution" title="身份映射与语义对齐" description="把 CRM customer_id、ERP buyer_code 等异构身份映射为统一企业对象 ID，并保留置信度、验证状态和证据责任。" actions={<Button className="rounded-xl bg-teal-300 text-[#061718] hover:bg-teal-200"><Plus className="mr-2 h-4 w-4" />添加映射规则</Button>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_380px]">
      <Panel title="跨系统身份图" eyebrow="Canonical identity"><div className="micro-grid relative min-h-[470px] overflow-hidden rounded-2xl border border-white/[0.05] bg-black/15 p-8"><div className="absolute left-1/2 top-1/2 grid h-36 w-36 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-orange-300/30 bg-orange-300/10 text-center shadow-[0_0_80px_rgba(196,92,35,.15)]"><Fingerprint className="h-6 w-6 text-orange-300" /><div><p className="text-xs font-semibold text-white">华星精密</p><p className="mt-1 font-mono text-[9px] text-orange-200">OBJ-C-1002</p></div></div>{customerMappings.map((item, index) => { const position = ["left-8 top-12", "right-8 top-16", "left-14 bottom-10"][index]; return <div key={`${item.system}-${item.field}`} className={`absolute ${position} w-52 rounded-2xl border border-teal-300/15 bg-[#0b292b]/95 p-4`}><div className="flex items-center justify-between"><Database className="h-4 w-4 text-teal-300" /><StatusBadge status={item.status} /></div><p className="mt-3 text-xs font-medium text-white">{item.system}</p><p className="mt-2 font-mono text-[10px] text-teal-200">{item.field}</p><p className="mt-1 font-mono text-xs text-slate-300">{item.value}</p><p className="mt-3 text-[9px] text-slate-600">置信度 {item.confidence}%</p></div>; })}<div className="absolute left-[24%] right-[24%] top-1/2 h-px bg-gradient-to-r from-teal-300/20 via-orange-300/35 to-teal-300/20" /></div></Panel>
      <div className="space-y-5"><Panel title="映射契约" eyebrow="Required example"><div className="rounded-xl border border-orange-300/15 bg-orange-300/[0.05] p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-orange-200">Identity contract</p><div className="mt-4 space-y-3 font-mono text-xs"><p className="text-slate-300"><span className="text-slate-600">CRM.</span>customer_id <ChevronRight className="mx-1 inline h-3 w-3" /> OBJ-C-1002</p><p className="text-slate-300"><span className="text-slate-600">ERP.</span>buyer_code <ChevronRight className="mx-1 inline h-3 w-3" /> OBJ-C-1002</p></div></div></Panel><Panel title="质量门" eyebrow="Resolution policy"><div className="space-y-3">{["名称相似度 ≥ 0.92", "税号或主数据编码精确匹配", "冲突映射必须人工复核", "映射变更写入审计事件"].map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/[0.04] bg-black/10 p-3 text-xs text-slate-300"><span className="grid h-6 w-6 place-items-center rounded-full bg-teal-300/10 text-teal-300"><Check className="h-3 w-3" /></span>{item}</div>)}</div></Panel><Panel title="对齐状态" eyebrow="Mapping health"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-black/15 p-4"><p className="text-2xl font-semibold text-white">98.6%</p><p className="mt-1 text-[9px] text-slate-600">已验证覆盖率</p></div><div className="rounded-xl bg-black/15 p-4"><p className="text-2xl font-semibold text-orange-200">12</p><p className="mt-1 text-[9px] text-slate-600">待复核冲突</p></div></div></Panel></div>
    </div></>;
}
